## Task 2 - Prediction of store sales

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
train_data =pd.read_csv('train.csv')

C:\Users\pooji\AppData\Local\Temp\ipykernel_26744\3616632472.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data =pd.read_csv('train.csv')


In [36]:
train_data

Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0            1          5  2015-07-31   5263        555     1      1   
1            2          5  2015-07-31   6064        625     1      1   
2            3          5  2015-07-31   8314        821     1      1   
3            4          5  2015-07-31  13995       1498     1      1   
4            5          5  2015-07-31   4822        559     1      1   
...        ...        ...         ...    ...        ...   ...    ...   
1017204   1111          2  2013-01-01      0          0     0      0   
1017205   1112          2  2013-01-01      0          0     0      0   
1017206   1113          2  2013-01-01      0          0     0      0   
1017207   1114          2  2013-01-01      0          0     0      0   
1017208   1115          2  2013-01-01      0          0     0      0   

        StateHoliday  SchoolHoliday  
0                  0              1  
1                  0              1  
2                  0              1  
3                  0              1  
4                  0              1  
...              ...            ...  
1017204            a              1  
1017205            a              1  
1017206            a              1  
1017207            a              1  
1017208            a              1  

[1017209 rows x 9 columns]

In [37]:
test_data=pd.read_csv("test.csv")

In [38]:
test_data

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  \
0          1      1          4  2015-09-17   1.0      1            0   
1          2      3          4  2015-09-17   1.0      1            0   
2          3      7          4  2015-09-17   1.0      1            0   
3          4      8          4  2015-09-17   1.0      1            0   
4          5      9          4  2015-09-17   1.0      1            0   
...      ...    ...        ...         ...   ...    ...          ...   
41083  41084   1111          6  2015-08-01   1.0      0            0   
41084  41085   1112          6  2015-08-01   1.0      0            0   
41085  41086   1113          6  2015-08-01   1.0      0            0   
41086  41087   1114          6  2015-08-01   1.0      0            0   
41087  41088   1115          6  2015-08-01   1.0      0            0   

       SchoolHoliday  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
41083              0  
41084              0  
41085              0  
41086              0  
41087              1  

[41088 rows x 8 columns]

In [39]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Store          1017209 non-null  int64 
 1   DayOfWeek      1017209 non-null  int64 
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64 
 4   Customers      1017209 non-null  int64 
 5   Open           1017209 non-null  int64 
 6   Promo          1017209 non-null  int64 
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64 
dtypes: int64(7), object(2)
memory usage: 69.8+ MB


In [68]:
train_data['Date']=pd.to_datetime(train_data['Date'])

In [73]:
train_data['StateHoliday']=train_data['StateHoliday'].replace({'0':'NoHoliday','a':'PublicHoliday','b':'EasterHoliday','c':'ChristmasHoliday'})

In [74]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype         
---  ------         --------------    -----         
 0   Store          1017209 non-null  int64         
 1   DayOfWeek      1017209 non-null  int64         
 2   Date           1017209 non-null  datetime64[ns]
 3   Sales          1017209 non-null  int64         
 4   Customers      1017209 non-null  int64         
 5   Open           1017209 non-null  int64         
 6   Promo          1017209 non-null  int64         
 7   StateHoliday   1017209 non-null  object        
 8   SchoolHoliday  1017209 non-null  int64         
dtypes: datetime64[ns](1), int64(7), object(1)
memory usage: 69.8+ MB


In [75]:
train_data['StateHoliday'].unique()

array(['NoHoliday', 'PublicHoliday', 'EsterHoliday', 'ChristmasHoliday'],
      dtype=object)

In [76]:
train_data['StateHoliday']=train_data['StateHoliday'].replace({'NoHoliday':0, 'PublicHoliday':1, 'EsterHoliday':2, 'ChristmasHoliday':3})

In [45]:
train_data['Date']

0         2015-07-31
1         2015-07-31
2         2015-07-31
3         2015-07-31
4         2015-07-31
             ...    
1017204   2013-01-01
1017205   2013-01-01
1017206   2013-01-01
1017207   2013-01-01
1017208   2013-01-01
Name: Date, Length: 1017209, dtype: datetime64[ns]

In [46]:
train_data.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [80]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Id             41088 non-null  int64         
 1   Store          41088 non-null  int64         
 2   DayOfWeek      41088 non-null  int64         
 3   Date           41088 non-null  datetime64[ns]
 4   Open           41088 non-null  int64         
 5   Promo          41088 non-null  int64         
 6   StateHoliday   41088 non-null  int64         
 7   SchoolHoliday  41088 non-null  int64         
dtypes: datetime64[ns](1), int64(7)
memory usage: 2.5 MB


In [48]:
test_data['StateHoliday'].unique()

array(['0', 'a'], dtype=object)

In [49]:
test_data['StateHoliday']=test_data['StateHoliday'].replace({'0':'NoHoliday','a':'PublicHoliday'})

In [50]:
test_data['StateHoliday'].unique()

array(['NoHoliday', 'PublicHoliday'], dtype=object)

In [78]:
test_data['StateHoliday']=test_data['StateHoliday'].replace({'NoHoliday':0, 'PublicHoliday':1})

In [51]:
test_data['Date']=pd.to_datetime(test_data['Date'])

In [52]:
test_data['Date']

0       2015-09-17
1       2015-09-17
2       2015-09-17
3       2015-09-17
4       2015-09-17
           ...    
41083   2015-08-01
41084   2015-08-01
41085   2015-08-01
41086   2015-08-01
41087   2015-08-01
Name: Date, Length: 41088, dtype: datetime64[ns]

In [25]:
test_data.isnull().sum()

Id                0
Store             0
DayOfWeek         0
Date              0
Open             11
Promo             0
StateHoliday      0
SchoolHoliday     0
dtype: int64

In [57]:
test_data['Open']= test_data['Open'].fillna(method='ffill')

In [58]:
test_data['Open'] = test_data['Open'].round().astype('int64')

In [60]:
test_data.isnull().sum()

Id               0
Store            0
DayOfWeek        0
Date             0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [79]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Id             41088 non-null  int64         
 1   Store          41088 non-null  int64         
 2   DayOfWeek      41088 non-null  int64         
 3   Date           41088 non-null  datetime64[ns]
 4   Open           41088 non-null  int64         
 5   Promo          41088 non-null  int64         
 6   StateHoliday   41088 non-null  int64         
 7   SchoolHoliday  41088 non-null  int64         
dtypes: datetime64[ns](1), int64(7)
memory usage: 2.5 MB


In [84]:
train_data['DayOfWeek'].unique()

array([5, 4, 3, 2, 1, 7, 6], dtype=int64)

## Extract Weekdays

In [89]:
train_data['weekday'] = (train_data['DayOfWeek']<=5).astype('int64')

In [90]:
train_data['weekday'].unique()

array([1, 0], dtype=int64)

## Extract Weekend

In [93]:
train_data['weekend']=train_data['DayOfWeek'].isin([6,7]).astype('int64')

In [96]:
train_data['weekend'].unique()

array([0, 1], dtype=int64)

##### This code will assign a value of 1 to the 'weekday' column if the 'DayOfWeek' is less than or equal to 5 (Monday to Friday), and 0 otherwise. The .astype(int) function is applied after the boolean comparison to convert the resulting boolean values (True or False) to integers (1 or 0).

##### This will create a new column where the value is 1 if the 'DayOfWeek' is 6 (Saturday) or 7 (Sunday), and 0 otherwise (indicating a weekday). The isin() function is used to check if the 'DayOfWeek' is in the list [6, 7], which corresponds to Saturday and Sunday.

## Number of days to Holidays

In [100]:
train_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'weekday', 'weekend'],
      dtype='object')

In [106]:
def count_holidays(row):
    is_holiday = row['StateHoliday'] != 0 or row['SchoolHoliday'] != 0 or row['DayOfWeek'] ==7
    return int(is_holiday)

train_data['is_holiday'] = train_data.apply(count_holidays, axis=1)
total_holidays = train_data['is_holiday'].sum()

print("Total number of holidays:", total_holidays)

Total number of holidays: 338957
